# Generated by Django 5.1.5 on 2025-03-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodingGrounds', '0002_gameparticipation_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
