# Generated by Django 5.1.5 on 2025-04-28 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodingGrounds', '0003_alter_gamesession_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='codingprofile',
            name='CodingGroun_usernam_ffe44a_idx',
        ),
        migrations.RemoveField(
            model_name='codingprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='codingprofile',
            name='username',
        ),
        migrations.AddIndex(
            model_name='codingprofile',
            index=models.Index(fields=['user'], name='CodingGroun_user_id_9eb337_idx'),
        ),
    ]
