# Generated by Django 5.1.5 on 2025-05-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodingGrounds', '0004_remove_codingprofile_codinggroun_usernam_ffe44a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='max_participants',
            field=models.IntegerField(default=2, help_text='0 for unlimited'),
        ),
    ]
