# Generated by Django 5.1.5 on 2025-05-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodingGrounds', '0005_alter_gamesession_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameparticipation',
            name='rating_change',
            field=models.IntegerField(default=0, help_text='Change in rating after the session'),
        ),
    ]
